### PR TITLE
add setStart method

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Like was done for joomla cms
https://github.com/joomla/joomla-cms/pull/8888

### CODE REVIEW

**Comment by mbabker** [comment]
Unfortunately there are a few issues with just adding this (since the profiler API here is different than the CMS'):

The memory line in the new method shouldn't have any division in it (see the mark method where these values are set if no points are defined).

... which leads into a second issue.  Running this code, the start points would be reset:

``` php
(new Profiler)->setStart($time, $memory)->mark('afterLoad');
```

So this method as is would only work if a point has already been defined.  And that gets into yet another issue.  If you get into the mark method, you'll see the ProfilePoint object is created by running a math operation on the current time/memory and the start time/memory to figure out the data for the point.

FWIW, I ran into something similar in something I was messing with and this was the working code solution I came up with.

Instantiate the profiler:

``` php
$startPoint = new \Joomla\Profiler\ProfilePoint('boot');

(new ExtendedProfiler('Application', null, [$startPoint]))->mark('afterBoot');
```

Extended profiler class:

``` php
class ExtendedProfiler extends \Joomla\Profiler\Profiler
{
    public function __construct($name, \Joomla\Profiler\ProfilerRendererInterface $renderer = null, array $points = array(), $memoryRealUsage = false)
    {
        parent::__construct($name, $renderer, $points, $memoryRealUsage);

        $this->startMemoryBytes = CONSTANT_FOR_STARTING_MEMORY;
        $this->startTimeStamp   = CONSTANT_FOR_STARTING_TIME;
    }
}
```

I guess using a combination of the constructor argument and your setStart method this call chain could work:

``` php
$startPoint = new \Joomla\Profiler\ProfilePoint('boot');

(new Profiler('Application', null, [$startPoint]))->setStart($time, $memory)->mark('afterBoot');
```

Off hand I can't think of anything "better" for this the way this code is written, but as is the new method just won't work the same way as the CMS' profiler class.

**Comment by andrepereiradasilva** [comment]
i understand what you mean. Since i don't use the framework, i leave it up to you if you think is merge worth it this way or close it.

**Comment by mbabker** [comment]
Expanded the method to add the needed checks and merged.

**Comment by andrepereiradasilva** [comment]
cool thanks!

**Pull request merged**
